/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as InboxRouteImport } from './routes/inbox';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CasesIdRouteImport } from './routes/cases.$id';
import { Route as CasesIdTraceRouteImport } from './routes/cases.$id.trace';
const InboxRoute = InboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const CasesIdRoute = CasesIdRouteImport.update({
    id: '/cases/$id',
    path: '/cases/$id',
    getParentRoute: () => rootRouteImport,
});
const CasesIdTraceRoute = CasesIdTraceRouteImport.update({
    id: '/trace',
    path: '/trace',
    getParentRoute: () => CasesIdRoute,
});
const CasesIdRouteChildren = {
    CasesIdTraceRoute: CasesIdTraceRoute,
};
const CasesIdRouteWithChildren = CasesIdRoute._addFileChildren(CasesIdRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    InboxRoute: InboxRoute,
    CasesIdRoute: CasesIdRouteWithChildren,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
