/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CasesIdTraceRouteImport } from './routes/cases.$id.trace'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdTraceRoute = CasesIdTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => CasesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/cases/$id': typeof CasesIdRouteWithChildren
  '/cases/$id/trace': typeof CasesIdTraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/cases/$id': typeof CasesIdRouteWithChildren
  '/cases/$id/trace': typeof CasesIdTraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/cases/$id': typeof CasesIdRouteWithChildren
  '/cases/$id/trace': typeof CasesIdTraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inbox' | '/cases/$id' | '/cases/$id/trace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inbox' | '/cases/$id' | '/cases/$id/trace'
  id: '__root__' | '/' | '/inbox' | '/cases/$id' | '/cases/$id/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  CasesIdRoute: typeof CasesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id/trace': {
      id: '/cases/$id/trace'
      path: '/trace'
      fullPath: '/cases/$id/trace'
      preLoaderRoute: typeof CasesIdTraceRouteImport
      parentRoute: typeof CasesIdRoute
    }
  }
}

interface CasesIdRouteChildren {
  CasesIdTraceRoute: typeof CasesIdTraceRoute
}

const CasesIdRouteChildren: CasesIdRouteChildren = {
  CasesIdTraceRoute: CasesIdTraceRoute,
}

const CasesIdRouteWithChildren =
  CasesIdRoute._addFileChildren(CasesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  CasesIdRoute: CasesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
